name: flutter_authentication
description: Flutter application for authentication.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  dio: ^5.3.0
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_secure_storage: ^8.0.0
  flutter_svg: ^2.0.7
  provider: ^6.0.5

dev_dependencies:
  build_runner: ^2.4.6
  flutter_gen_runner: ^5.3.1
  flutter_lints: ^2.0.2
  flutter_test:
    sdk: flutter

flutter_gen:
integrations:
  flutter_svg: true

assets:
  output:
    enabled: true
    package_parameter_enabled: true
    style: camel-case

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/icons/
